In [ ]:
# optimizers -----> it will minimize the loss function(Actual - Prediction)

# Stocastic Gradient Descent -----> it is stucking in local minima
# SGD + Momentum -----> Momentum = 0.9 , it resolve issue but does not completely .

# SGD + Momentum + NAG(Nestrovb Accelerated Gradient)  ---> it resolve the issue of stucking in local minima
# by calculating the previous Squared gradient + feature squared gradients for direction

# AdaGrad ----> it provide automatic learning rate concept

# RMSProp ----> it resolve this automatic learning rate issue by adding an epslon term .

# Adam ---> it is the combination of 2 optimizers (momentum+ NAG , RMSProp)

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Attrition.csv")

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df = df.dropna()

In [ ]:
x = df.drop(columns = ['Attrition'], axis = 1)
y = df['Attrition']

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [ ]:
categorical_features = ['BusinessTravel',
                        'Department',
                        'EducationField',
                        'Gender',
                        'JobRole',
                        'MaritalStatus',
                        'Over18',
                        'OverTime']

In [ ]:
x_encoded = pd.get_dummies(x,columns = categorical_features ,
                           drop_first = True)

In [ ]:
x_encoded = x_encoded.astype(int)
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,1,0,0,0,0,0,0,1,0,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,0,0,1,0,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,1,0,0,0,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,0,0,0,1,0,1,0,0
1469,34,628,8,3,1,2068,2,82,4,2,...,1,0,0,0,0,0,0,1,0,0

In [ ]:
# encode traget data
lb = LabelEncoder()

In [ ]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
x_train , x_test , y_train , y_test = train_test_split (x_encoded ,
                                                        y_encoded ,
                                                        test_size = 0.2 ,
                                                        random_state =42)

In [ ]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [ ]:
# NOW WE WILL CREATE ARCHITECTURE OF OUR MODEL

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units = 128 , activation = 'relu',
                          input_dim = x_train_scaled.shape[1]),     #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 64 , activation = 'relu'),        #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1 , activation = 'sigmoid')         #output layer
])

# Units = Number of neurons in that layer

In [ ]:
# compile the model

In [ ]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

In [ ]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers.SGD(learning_rate = learning_rate ,
                                    momentum = momentum , nesterov = True )

In [ ]:
model.compile(optimizer = optimizer , loss = loss_fn , metrics = metrics )

In [ ]:
# train the model

In [ ]:
model.fit(x_train_scaled , y_train ,
          epochs = 50 ,
          batch_size = 8,
          validation_split = 0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8043 - loss: 0.5079 - val_accuracy: 0.7966 - val_loss: 0.5186
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8242 - loss: 0.4382 - val_accuracy: 0.7966 - val_loss: 0.4892
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8289 - loss: 0.4486 - val_accuracy: 0.7966 - val_loss: 0.4670
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8318 - loss: 0.4239 - val_accuracy: 0.7966 - val_loss: 0.4520
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8308 - loss: 0.4008 - val_accuracy: 0.7966 - val_loss: 0.4401
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8450 - loss: 0.3996 - val_accuracy: 0.8051 - val_loss: 0.4247
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8459 - loss: 0.3874 - val_accuracy: 0.8305 - val_loss: 0.4159
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8526 - loss: 0.3629 - val_accuracy: 0.8220 - val_loss: 0.4075
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8516 - loss: 0.3472 - val_accuracy: 0.8220 - val_loss: 0.3966
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8507 - loss: 0.3474 - val_accuracy: 0.8305 - val_loss: 0.3917
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8535 - loss: 0.3569 - val_accuracy: 0.8305 - val_loss: 0.3846
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8629 - loss: 0.3436 - val_accuracy: 0.8305 - val_loss: 0.3803
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8743 - loss: 0.3336 - val_accuracy: 0.8390 - val_loss: 0.3776
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8762 - loss: 0.3216 - val_accuracy: 0.8390 - val_loss: 0.3721
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8724 - loss: 0.3141 - val_accuracy: 0.8475 - val_loss: 0.3691
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8800 - loss: 0.2985 - val_accuracy: 0.8305 - val_loss: 0.3655
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8837 - loss: 0.3023 - val_accuracy: 0.8305 - val_loss: 0.3652
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8733 - loss: 0.3083 - val_accuracy: 0.8305 - val_loss: 0.3615
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8932 - loss: 0.2876 - val_accuracy: 0.8305 - val_loss: 0.3657
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8856 - loss: 0.2889 - val_accuracy: 0.8136 - val_loss: 0.3637
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8875 - loss: 0.2903 - val_accuracy: 0.8051 - val_loss: 0.3629
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8989 - loss: 0.2796 - val_accuracy: 0.8136 - val_loss: 0.3571
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.8894 - loss: 0.2714 - val_accuracy: 0.8220 - val_loss: 0.3607
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8913 - loss: 0.2693 - val_accuracy: 0.8051 - val_loss: 0.3636
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8847 - loss: 0.2834 - val_accuracy: 0.8136 - val_loss: 0.3626
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8856 - loss: 0.2722 - val_accuracy: 0.8220 - val_loss: 0.3656
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2571 - val_accuracy: 0.8136 - val_loss: 0.3625
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8875 - loss: 0.2605 - val_accuracy: 0.8051 - val_loss: 0.3662
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2684 - val_accuracy: 0.8051 - val_loss: 0.3690
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9045 - loss: 0.2359 - val_accuracy: 0.7966 - val_loss: 0.3696
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2513 - val_accuracy: 0.7966 - val_loss: 0.3705
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9045 - loss: 0.2362 - val_accuracy: 0.8136 - val_loss: 0.3723
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8951 - loss: 0.2403 - val_accuracy: 0.8051 - val_loss: 0.3710
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9017 - loss: 0.2445 - val_accuracy: 0.8136 - val_loss: 0.3695
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2372 - val_accuracy: 0.8136 - val_loss: 0.3747
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9026 - loss: 0.2371 - val_accuracy: 0.8136 - val_loss: 0.3768
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9093 - loss: 0.2358 - val_accuracy: 0.8136 - val_loss: 0.3792
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9008 - loss: 0.2347 - val_accuracy: 0.7966 - val_loss: 0.3779
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9036 - loss: 0.2349 - val_accuracy: 0.8136 - val_loss: 0.3862
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9083 - loss: 0.2142 - val_accuracy: 0.7966 - val_loss: 0.3892
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2190 - val_accuracy: 0.7966 - val_loss: 0.4005
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9064 - loss: 0.2246 - val_accuracy: 0.7881 - val_loss: 0.4018
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9055 - loss: 0.2203 - val_accuracy: 0.7966 - val_loss: 0.3971
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9187 - loss: 0.2068 - val_accuracy: 0.7966 - val_loss: 0.4040
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9197 - loss: 0.1939 - val_accuracy: 0.7966 - val_loss: 0.4112
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9159 - loss: 0.2025 - val_accuracy: 0.7966 - val_loss: 0.4133
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9253 - loss: 0.1865 - val_accuracy: 0.8051 - val_loss: 0.4105
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9121 - loss: 0.1985 - val_accuracy: 0.7712 - val_loss: 0.4154
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9149 - loss: 0.1876 - val_accuracy: 0.7881 - val_loss: 0.4187
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9130 - loss: 0.1989 - val_accuracy: 0.7966 - val_loss: 0.4191

In [ ]:
loss , accuracy = model.evaluate(x_test_scaled ,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8776 - loss: 0.3530

In [ ]:
print(f'Test loss = {loss :.4f} , Test Accuracy = {accuracy :.4f}')

Test loss = 0.3530 , Test Accuracy = 0.8776

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")

In [ ]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
df = df.dropna()

In [ ]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     90 non-null     int64
 1   gender  90 non-null     object
 2   fever   90 non-null     float64
 3   cough   90 non-null     object
 4   city    90 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.2+ KB

In [ ]:
x['city'] = lb.fit_transform(x['city'])
x['cough'] = lb.fit_transform(x['cough'])
x['gender'] = lb.fit_transform(x['gender'])
y = lb.fit_transform(y)

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state=42)

In [ ]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [ ]:
# NOW WE WILL CREATE ARCHITECTURE OF OUR MODEL

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units = 128 , activation = 'relu',
                          input_dim = x_train_scaled.shape[1]),     #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 64 , activation = 'relu'),        #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1 , activation = 'sigmoid')         #output layer
])

In [ ]:
# compile the model

In [ ]:
loss_fn = tf.keras.losses.BinaryCrossentropy
metrics = ['accuracy']

In [ ]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers.SGD(learning_rate = learning_rate ,
                                    momentum = momentum , nesterov = True )

In [ ]:
model.compile(optimizer = optimizer , metrics = metrics , loss = loss_fn )

In [ ]:
model.fit(x_train_scaled , y_train ,
          epochs = 50 ,
          batch_size = 10,
          validation_split = 0.2)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - accuracy: 0.4737 - loss: 0.6987 - val_accuracy: 0.2667 - val_loss: 0.7357
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5088 - loss: 0.6908 - val_accuracy: 0.2667 - val_loss: 0.7337
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5789 - loss: 0.6770 - val_accuracy: 0.3333 - val_loss: 0.7312
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4737 - loss: 0.6979 - val_accuracy: 0.3333 - val_loss: 0.7284
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4912 - loss: 0.6786 - val_accuracy: 0.3333 - val_loss: 0.7260
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.5965 - loss: 0.6836 - val_accuracy: 0.3333 - val_loss: 0.7229
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5965 - loss: 0.6614 - val_accuracy: 0.4667 - val_loss: 0.7203
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.6140 - loss: 0.6611 - val_accuracy: 0.6000 - val_loss: 0.7176
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.5789 - loss: 0.6919 - val_accuracy: 0.6000 - val_loss: 0.7151
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5789 - loss: 0.6788 - val_accuracy: 0.6667 - val_loss: 0.7127
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5965 - loss: 0.6824 - val_accuracy: 0.6000 - val_loss: 0.7107
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5789 - loss: 0.6813 - val_accuracy: 0.6000 - val_loss: 0.7082
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5789 - loss: 0.6821 - val_accuracy: 0.6000 - val_loss: 0.7060
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5263 - loss: 0.7026 - val_accuracy: 0.6000 - val_loss: 0.7037
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6316 - loss: 0.6600 - val_accuracy: 0.6000 - val_loss: 0.7016
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7018 - loss: 0.6314 - val_accuracy: 0.6000 - val_loss: 0.6997
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4912 - loss: 0.6769 - val_accuracy: 0.6000 - val_loss: 0.6982
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5789 - loss: 0.6758 - val_accuracy: 0.6000 - val_loss: 0.6964
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5614 - loss: 0.6764 - val_accuracy: 0.6000 - val_loss: 0.6943
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6140 - loss: 0.6563 - val_accuracy: 0.6000 - val_loss: 0.6922
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5614 - loss: 0.6907 - val_accuracy: 0.6000 - val_loss: 0.6901
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5614 - loss: 0.6624 - val_accuracy: 0.6000 - val_loss: 0.6884
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5789 - loss: 0.6547 - val_accuracy: 0.6000 - val_loss: 0.6869
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6549 - val_accuracy: 0.6000 - val_loss: 0.6857
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6491 - loss: 0.6604 - val_accuracy: 0.6000 - val_loss: 0.6848
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6316 - loss: 0.6573 - val_accuracy: 0.6000 - val_loss: 0.6838
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5789 - loss: 0.6763 - val_accuracy: 0.6000 - val_loss: 0.6828
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5965 - loss: 0.6562 - val_accuracy: 0.6000 - val_loss: 0.6815
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6491 - loss: 0.6645 - val_accuracy: 0.6000 - val_loss: 0.6803
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6494 - val_accuracy: 0.6000 - val_loss: 0.6786
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5789 - loss: 0.6650 - val_accuracy: 0.6000 - val_loss: 0.6770
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6620 - val_accuracy: 0.6000 - val_loss: 0.6752
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5614 - loss: 0.6476 - val_accuracy: 0.6667 - val_loss: 0.6736
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6140 - loss: 0.6722 - val_accuracy: 0.6667 - val_loss: 0.6722
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.6374 - val_accuracy: 0.6667 - val_loss: 0.6707
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6140 - loss: 0.6381 - val_accuracy: 0.6667 - val_loss: 0.6694
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5965 - loss: 0.6679 - val_accuracy: 0.6667 - val_loss: 0.6678
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6420 - val_accuracy: 0.6667 - val_loss: 0.6666
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.6421 - val_accuracy: 0.6667 - val_loss: 0.6655
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6536 - val_accuracy: 0.6667 - val_loss: 0.6643
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6491 - loss: 0.6374 - val_accuracy: 0.6667 - val_loss: 0.6634
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6491 - loss: 0.6286 - val_accuracy: 0.6667 - val_loss: 0.6625
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6608 - val_accuracy: 0.6667 - val_loss: 0.6611
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7193 - loss: 0.6326 - val_accuracy: 0.6667 - val_loss: 0.6596
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6341 - val_accuracy: 0.6667 - val_loss: 0.6581
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7018 - loss: 0.6277 - val_accuracy: 0.6667 - val_loss: 0.6569
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6491 - loss: 0.6345 - val_accuracy: 0.6667 - val_loss: 0.6558
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6212 - val_accuracy: 0.6667 - val_loss: 0.6541
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6316 - loss: 0.6286 - val_accuracy: 0.6667 - val_loss: 0.6525
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.6337 - val_accuracy: 0.6667 - val_loss: 0.6511

In [ ]:
loss , accuracy = model.evaluate(x_test_scaled ,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step - accuracy: 0.5000 - loss: 0.7273

In [ ]:
print(f'Test loss = {loss :.4f} , Test Accuracy = {accuracy :.4f}')

Test loss = 0.7273 , Test Accuracy = 0.5000

In [ ]:
df = pd.read_csv("")