In [ ]:
# Column Transformer
# is used to apply different preprocessing techniques to different columns of a dataset simultaneously

In [ ]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(
    df.drop(columns =['has_covid']),
    df['has_covid'],
    test_size = 0.2,
    random_state= 1)

In [ ]:
x_train

    age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
75    5    Male  102.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

#Manually type output

In [ ]:
# adding simple imputer to fever column

si = SimpleImputer(strategy ='mean')
x_train_fever = si.fit_transform(x_train[['fever']])


# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [ ]:
# ordinal Encoding ----> cough

oe = OrdinalEncoder(categories = [['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data

x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [ ]:
# onehotEncoder ---> Gender , city

ohe = OneHotEncoder(drop = 'first', sparse_output = False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [ ]:
# Extracting Age

x_train_age = x_train.drop(columns = ['gender','fever','cough','city']).values


# also the test data

x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values

In [ ]:
x_train_age.shape

(80, 1)

In [ ]:
x_train_transfromed = np.concatenate((x_train_age,x_train_fever,
                                     x_train_gender_city,x_train_cough),axis = 1 )

In [ ]:
x_test_transfromed = np.concatenate((x_test_age,x_test_fever,
                                     x_test_gender_city,x_test_cough),axis = 1 )

In [ ]:
x_train_transfromed.shape

(80, 7)

#by the help of column Transformer

In [ ]:
from sklearn.compose import ColumnTransformer

# constant
# approach
# columns name

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']) ,           #in a 'fever' column by the help of  SI

    # we fill missing values by mean , median , mode
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),

    # by this process we encode the data
    ('tnf3',OneHotEncoder(sparse_output = False , drop = 'first'),['gender','city'])

] , remainder='passthrough')
  #remainder = passthrough ==>
# it means rest all the columns remain same

In [ ]:
transformer.fit_transform(x_train).shape

(80, 7)

In [ ]:
transformer.fit_transform(x_test).shape

(20, 7)

In [ ]:
import seaborn as sns

In [ ]:
a = sns.load_dataset('tips')
a

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
a = a.drop(columns = ['size'])

In [ ]:
a.shape

(244, 6)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(a.drop(columns = ['total_bill']),
                                                       a['total_bill'],test_size = 0.2,
                                                       random_state = 1)

In [ ]:
x_train.shape

(195, 5)

In [ ]:
oe = OrdinalEncoder(categories=[['Female','Male']])

x_train_sex = oe.fit_transform(x_train[['sex']])
x_test_sex = oe.fit_transform(x_test[['sex']])

In [ ]:
x_train_sex.shape

(195, 1)

In [ ]:
ohe = OneHotEncoder(drop = 'first', sparse_output = False)
x_train_dt = ohe.fit_transform(x_train[['time','day','smoker']])

In [ ]:
x_test_dt = ohe.fit_transform(x_test[['time','day','smoker']])
x_train_dt.shape

(195, 5)

In [ ]:
x_train_tips = x_train.drop(columns = ['sex','smoker','day','time']).values

In [ ]:
x_test_tips = x_test.drop(columns = ['sex','smoker','day','time']).values

In [ ]:
x_train_tips.shape

(195, 1)

In [ ]:
transformed = np.concatenate((x_train_tips,x_train_sex,x_train_dt),axis = 1)

In [ ]:
x_test_transformed = np.concatenate((x_test_tips,x_test_sex,x_test_dt), axis = 1)

In [ ]:
transformed.shape

(195, 7)

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers = [
    ('a',OrdinalEncoder(categories = [['Female','Male']]),['sex']),
    ('b',OneHotEncoder(sparse_output = False , drop = 'first'),['time','day','smoker']),

],remainder = 'passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(195, 7)

In [ ]:
transformer.fit_transform(x_test).shape

(49, 7)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/credit_scoring.csv")
df.head()

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685.0,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371.0,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771.0,6,957000,2.76,12,Auto Loan
3,58,Female,Married,PhD,Unemployed,0.12,1371.0,2,4731000,6.57,60,Auto Loan
4,32,Male,Married,Bachelor,Self-Employed,0.99,828.0,2,3289000,6.28,36,Personal Loan

In [ ]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns = 'Loan Amount'), df['Loan Amount'],test_size=0.2,random_state = 1)

In [ ]:
x_train.shape

(800, 11)

In [ ]:
x_test.shape

(200, 11)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df['Marital Status'].value_counts()

Marital Status
Married     350
Divorced    326
Single      324
Name: count, dtype: int64

In [ ]:
oe = OrdinalEncoder(categories = [['Male','Female']])
x_train_gender=oe.fit_transform(x_train[['Gender']])

x_test_gender = oe.fit_transform(x_test[['Gender']])

x_train_gender.shape

(800, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(sparse_output = False , drop = 'first')
x_train_mee = ohe.fit_transform(x_train[["Marital Status",'Education Level','Employment Status']])

In [ ]:
x_test_mee = ohe.fit_transform(x_test[["Marital Status",'Education Level','Employment Status']])

In [ ]:
x_train_mee.shape

(800, 7)

In [ ]:
x_train['Type of Loan'].value_counts()

Type of Loan
Auto Loan        279
Personal Loan    261
Home Loan        260
Name: count, dtype: int64

In [ ]:
oe = OrdinalEncoder(categories = [['Auto Loan','Personal Loan','Home Loan']])
x_train_loan = oe.fit_transform(x_train[["Type of Loan"]])

In [ ]:
x_test_loan = oe.fit_transform(x_test[['Type of Loan']])

In [ ]:
x_train_loan.shape

(800, 1)

In [ ]:
x_train_numerical = x_train.select_dtypes(include = 'number').values

In [ ]:
x_test_numerical = x_test.select_dtypes(include = 'number').values

In [ ]:
x_train_transformed = np.concatenate((x_train_numerical,x_train_gender ,x_train_mee,x_train_loan ),axis = 1)

In [ ]:
x_train_transformed.shape

(800, 15)

#column transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('a',OrdinalEncoder(categories = [['Male','Female'],['Auto Loan','Personal Loan','Home Loan']]),['Gender','Type of Loan']),
    ('b',OneHotEncoder(sparse_output=False , drop= 'first'),["Marital Status",'Education Level','Employment Status'])
],remainder ='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(800, 15)

In [ ]:
df1 = pd.read_csv("/content/insurance.csv")
df1.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df1.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(df1.drop(columns = ['charges']), df1['charges'],test_size = 0.2,random_state = 1)

In [ ]:
x_train.shape

(1070, 6)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories = [['female','male']])
x_train_sex = oe.fit_transform(x_train[['sex']])
x_test_sex = oe.fit_transform(x_test[['sex']])

In [ ]:
x_train_sex.shape

(1070, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(sparse_output = False , drop = 'first')
x_train_smoker_region = ohe.fit_transform(x_train[['smoker','region']])
x_test_smoker_region = ohe.fit_transform(x_test[['smoker','region']])

In [ ]:
x_train_smoker_region.shape

(1070, 4)

In [ ]:
x_num = x_train.select_dtypes(include='number').values

In [ ]:
x_test_num = x_test.select_dtypes(include = 'number').values

In [ ]:
x_train_transform = np.concatenate((x_num , x_train_sex , x_train_smoker_region),axis = 1)

In [ ]:
x_test_transform = np.concatenate((x_test_num,x_test_sex,x_test_smoker_region),axis = 1)

In [ ]:
x_train_transform.shape

(1070, 8)

#column transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('a',OrdinalEncoder(categories=[['male','female']]),['sex']),
    ('b',OneHotEncoder(drop = 'first',sparse_output = False),('smoker','region'))
],remainder = 'passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(1070, 8)