#ENCODING

In [ ]:
# ENCODING ---> transform your categorical data into numerical data
# (1) Label ----> it will encode data 1-1 columns .
# (2) Ordinal ---> it will encode data more than 1 columns .
# (3) Onehot -----> it will create new column based on sub-categories but it has only  value not column name
# (4) get_dummies ----> it will create new column based on sub categories but it show column name with values

# LabelEncoder

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/toyota.csv")
df.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [ ]:
x = df.drop(columns =['price'])
y = df['price']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['model']  = lb.fit_transform(x['model'])
x['transmission'] = lb.fit_transform(x['transmission'])
x['fuelType'] = lb.fit_transform(x['fuelType'])

In [ ]:
x.head(3)

   model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0      6  2016             1    24089         3  265  36.2         2.0
1      6  2017             1    18615         3  145  36.2         2.0
2      6  2015             1    27469         3  265  36.2         2.0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size =0.2,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc= StandardScaler()

In [ ]:
x_train_sc= sc.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc,columns = x_train.columns)

In [ ]:
np.round(x_train_new.describe() , 2)

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
count,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00
mean,0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.18,-8.27,-1.02,-1.19,-1.97,-1.27,-3.67,-3.37
25%,-0.89,-0.36,-1.02,-0.70,-1.05,-1.27,-0.47,-1.08
50%,-0.46,0.11,0.49,-0.23,0.78,0.54,-0.10,0.06
75%,1.28,0.57,0.49,0.43,0.78,0.68,0.46,0.74
max,1.28,1.50,3.51,7.95,0.78,6.33,10.45,6.91

In [ ]:
df1= pd.read_csv("/content/covid_toy.csv")
df1.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df1['fever'] = df1['fever'].fillna(df1['fever'].mean())

In [ ]:
df1.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
x = df1.drop(columns =['has_covid'])
y = df1['has_covid']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
x['city'] = lb.fit_transform(x['city'])
x['cough'] = lb.fit_transform(x['cough'])
x['gender'] = lb.fit_transform(x['gender'])

In [ ]:
x.head(2)

   age  gender  fever  cough  city
0   60       1  103.0      0     2
1   27       1  100.0      0     1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc= StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_new = pd.DataFrame(x_train_sc,columns = x_train.columns)

In [ ]:
np.round(x_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean   -0.00   -0.00   0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.86  -1.49  -0.77  -1.20
25%    -0.96   -0.86  -0.98  -0.77  -1.20
50%     0.05   -0.86   0.03  -0.77  -0.29
75%     0.86    1.16   0.66   1.29   0.61
max     1.63    1.16   1.54   1.29   1.52

In [ ]:
df2= pd.read_csv("/content/Attrition.csv")
df2.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df2.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [ ]:
x = df2.drop(columns = ['Attrition'])

In [ ]:
y = df2['Attrition']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['Department'] = lb.fit_transform(x['Department'])
x['BusinessTravel'] = lb.fit_transform(x['BusinessTravel'])
x['EducationField'] = lb.fit_transform(x['EducationField'])
x['Gender'] = lb.fit_transform(x['Gender'])
x['JobRole'] = lb.fit_transform(x['JobRole'])
x['MaritalStatus'] = lb.fit_transform(x['MaritalStatus'])
x['OverTime'] = lb.fit_transform(x['OverTime'])
x['Over18'] = lb.fit_transform(x['Over18'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 ,random_state=1 )

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc= StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1176.00,1176.00,1176.00,1176.00,1176.00,1176.00,1176.00,1176.0,1176.00,1176.00,...,1176.00,1176.0,1176.00,1176.00,1176.00,1176.00,1176.00,1176.00,1176.00,1176.00
mean,0.00,-0.00,-0.00,0.00,0.00,0.00,0.00,0.0,-0.00,-0.00,...,0.00,0.0,0.00,0.00,-0.00,0.00,0.00,-0.00,-0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.0,1.00,1.00,...,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.09,-2.40,-1.75,-2.39,-1.01,-1.89,-1.69,0.0,-1.69,-1.58,...,-1.64,0.0,-0.93,-1.45,-2.19,-2.49,-1.16,-1.16,-0.67,-1.18
25%,-0.78,-0.91,-0.83,-0.48,-0.89,-0.91,-0.94,0.0,-0.89,-0.66,...,-0.70,0.0,-0.93,-0.68,-0.63,-1.06,-0.65,-0.61,-0.67,-0.60
50%,-0.12,0.59,-0.00,-0.48,-0.27,0.07,-0.19,0.0,-0.01,0.25,...,0.24,0.0,0.25,-0.17,0.15,0.36,-0.32,-0.34,-0.35,-0.32
75%,0.65,0.59,0.86,1.42,0.59,1.06,0.56,0.0,0.90,1.17,...,1.18,0.0,0.25,0.48,0.15,0.36,0.36,0.77,-0.04,0.83
max,2.51,0.59,1.70,1.42,2.44,2.04,2.05,0.0,1.72,1.17,...,1.18,0.0,2.61,3.69,2.48,1.78,5.56,3.80,4.02,3.69

#Ordinal Encoder

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.drop(columns = ['age' ,'fever'])

In [ ]:
df.head(2)

  gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['Kolkata','Bangalore','Delhi','Mumbai'],['Yes','No']])

In [ ]:
df_ar = oe.fit_transform(df)

In [ ]:
df_new = pd.DataFrame(df_ar , columns = df.columns)

In [ ]:
df_new

    gender  cough  city  has_covid
0      0.0    0.0   0.0        1.0
1      0.0    0.0   2.0        0.0
2      0.0    0.0   2.0        1.0
3      1.0    0.0   0.0        1.0
4      1.0    0.0   3.0        1.0
..     ...    ...   ...        ...
95     1.0    0.0   1.0        1.0
96     1.0    1.0   0.0        0.0
97     1.0    0.0   1.0        1.0
98     1.0    1.0   3.0        1.0
99     1.0    1.0   0.0        0.0

[100 rows x 4 columns]

#oneHot encoding
column has_covid ['y' ,'n'] ----> new column y_has_covid , n_has_covid ----> but contain only values not column name

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns =['age','fever'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False , dtype = np.int32)
#sparse_output =>  to return a dense NumPy array

In [ ]:
# gender ---> 2 -1 = 1
# cough ----> 2- 1 = 1
# city -----> 4- 1 = 3
# has_covid ---> 2- 1 = 1

In [ ]:
ohe.fit_transform(df[['gender','cough','city','has_covid']])

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1]], dtype=int32)

In [ ]:
a = ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [ ]:
# Convert to DataFrame
encoded_df = pd.DataFrame(a,
    columns=ohe.get_feature_names_out(['gender','cough','city','has_covid']))

encoded_df.head()

,gender_Male,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,1,0,0,1,0,0
1,1,0,1,0,0,1
2,1,0,1,0,0,0
3,0,0,0,1,0,0
4,0,0,0,0,1,0

#get_dummies -----> pandas method

In [ ]:
a = pd.get_dummies(df , columns = ['gender','cough','city','has_covid'], drop_first=True)

In [ ]:
a = a.astype(int)
a

,gender_Male,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,1,0,0,1,0,0
1,1,0,1,0,0,1
2,1,0,1,0,0,0
3,0,0,0,1,0,0
4,0,0,0,0,1,0
...,...,...,...,...,...,...
95,0,0,0,0,0,0
96,0,1,0,1,0,1
97,0,0,0,0,0,0
98,0,1,0,0,1,0
99,0,1,0,1,0,1

In [ ]:
a = pd.read_csv("/content/toyota.csv")
a.head(2)

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
a = a.drop(columns = 'year')
a.head(2)

   model  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
a.isnull().sum()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
a['model'] = lb.fit_transform(a['model'])

In [ ]:
a['transmission'] = lb.fit_transform(a['transmission'])
a['fuelType'] = lb.fit_transform(a['fuelType'])

In [ ]:
a

      model  price  transmission  mileage  fuelType  tax   mpg  engineSize
0         6  16000             1    24089         3  265  36.2         2.0
1         6  15995             1    18615         3  145  36.2         2.0
2         6  13998             1    27469         3  265  36.2         2.0
3         6  18998             1    14736         3  150  36.2         2.0
4         6  17498             1    36284         3  145  36.2         2.0
...     ...    ...           ...      ...       ...  ...   ...         ...
6733      8   5500             0    30000         3   20  58.9         1.0
6734     14   4985             1    36154         3  125  50.4         1.3
6735     14   4995             1    46000         0  125  57.6         1.4
6736     14   3995             1    60700         3  125  50.4         1.3
6737     14   4495             1    45128         3  125  50.4         1.3

[6738 rows x 8 columns]

In [ ]:
b = pd.read_csv("/content/toyota.csv")
b.head(2)

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
b = b.drop(columns =['year','model','price','mileage','tax','mpg','engineSize'])

In [ ]:
b.head()

  transmission fuelType
0       Manual   Petrol
1       Manual   Petrol
2       Manual   Petrol
3       Manual   Petrol
4       Manual   Petrol

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
b['fuelType'].value_counts()

fuelType
Petrol    4087
Hybrid    2043
Diesel     503
Other      105
Name: count, dtype: int64

In [ ]:
oe = OrdinalEncoder(categories =[['Manual','Automatic','Semi-Auto','Other'],['Petrol','Hybrid','Diesel','Other']])

In [ ]:
b1 = oe.fit_transform(b)

In [ ]:
b_new = pd.DataFrame(b1 , columns =b.columns)

In [ ]:
b_new.head()

   transmission  fuelType
0           0.0       0.0
1           0.0       0.0
2           0.0       0.0
3           0.0       0.0
4           0.0       0.0

In [ ]:
c = pd.read_csv('/content/toyota.csv')
c.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first' , sparse_output = False , dtype = np.int32 )

In [ ]:
ohe.fit_transform(c[['transmission ','fuelType']])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [ ]:
d = pd.read_csv("/content/toyota.csv")
d.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [ ]:
d = pd.get_dummies(d , columns =['model','transmission','fuelType'], drop_first = True)

In [ ]:
d = d.astype(int)

In [ ]:
d.head()

,year,price,mileage,tax,mpg,engineSize,model_ Avensis,model_ Aygo,model_ C-HR,model_ Camry,...,model_ Urban Cruiser,model_ Verso,model_ Verso-S,model_ Yaris,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2016,16000,24089,265,36,2,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,2017,15995,18615,145,36,2,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2015,13998,27469,265,36,2,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2017,18998,14736,150,36,2,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,2017,17498,36284,145,36,2,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df = pd.get_dummies(df , columns =['sex','smoker','day','time'],drop_first = True)

In [ ]:
df = df.astype(int)
df.head()

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16,1,2,1,1,0,0,1,1
1,10,1,3,0,1,0,0,1,1
2,21,3,3,0,1,0,0,1,1
3,23,3,2,0,1,0,0,1,1
4,24,3,4,1,1,0,0,1,1